package com.exxeta.java.k8s.operator.config;

public enum Environments {
    ELASTICSEARCH_USERNAME,
    ELASTICSEARCH_PASSWORD,
    ELASTICSEARCH_MASTER_HOSTNAME,
    ELASTICSEARCH_MASTER_PORT,
    ILM_POLICY_FORCE_UPDATE,
    PUT_INDEX_REQUEST_BODY,
    PUT_INDEX_TEMPLATE_REQUEST_BODY,
    BEATS,
    NAMESPACE_EXEMPTIONS,
    ALIAS_JSON,
    DRY_RUN,
    SLEEP_TIMER
}
